@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.aot

import com.labijie.infra.orm.aot.registerOrmPojoType
import com.labijie.orm.dummy.Status
import com.labijie.orm.dummy.TestEnum
import com.labijie.orm.dummy.otherpackage.NestedInterface
import java.lang.ClassLoader
import org.springframework.aot.hint.MemberCategory
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar

/**
 * SpringBoot runtime hint for orm tables
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.TestTable
 */
internal class OrmPojoRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    // Begin Table Pojo types hint register
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.Test")
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.Shop")
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.IntId")
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.DurationIdEntity")
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.MultiKey")
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.DescribeEnum")
    hints.registerOrmPojoType("com.labijie.orm.dummy.pojo.TestSimple")
    // Begin Column types hint register
    hints.reflection().registerType(TestEnum::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
    hints.reflection().registerType(NestedInterface.StatusEnum::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
    hints.reflection().registerType(Status::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
  }
}
