@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.aot

import com.labijie.orm.dummy.Status
import com.labijie.orm.dummy.TestEnum
import com.labijie.orm.dummy.otherpackage.NestedInterface
import java.lang.ClassLoader
import org.springframework.aot.hint.MemberCategory
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar
import org.springframework.aot.hint.TypeReference

/**
 * SpringBoot runtime hint for orm tables
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: unknown
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.PostTable
 */
internal class OrmPojoRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    // Begin Table Pojo types hint register
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.Post")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.Shop")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.IntId")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.DurationIdEntity")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.MultiKey")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.DescribeEnum")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    hints.reflection().registerType(TypeReference.of("com.labijie.orm.dummy.pojo.TestSimple")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
    // Begin Column types hint register
    hints.reflection().registerType(TestEnum::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
    hints.reflection().registerType(NestedInterface.StatusEnum::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
    hints.reflection().registerType(Status::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
  }
}
