@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.aot

import com.labijie.orm.dummy.DescribeEnumTable
import com.labijie.orm.dummy.DurationIdEntityTable
import com.labijie.orm.dummy.IntIdTable
import com.labijie.orm.dummy.MultiKeyTable
import com.labijie.orm.dummy.PostTable
import com.labijie.orm.dummy.ShopTable
import com.labijie.orm.dummy.TestSimpleTable
import java.lang.ClassLoader
import org.springframework.aot.hint.MemberCategory
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar

/**
 * SpringBoot runtime hint for PostTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: unknown
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.PostTable
 */
public class OrmRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    hints.reflection().registerType(PostTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
    hints.reflection().registerType(ShopTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
    hints.reflection().registerType(IntIdTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
    hints.reflection().registerType(DurationIdEntityTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
    hints.reflection().registerType(TestSimpleTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
    hints.reflection().registerType(MultiKeyTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
    hints.reflection().registerType(DescribeEnumTable::class.java) {
      it.withMembers(MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_PUBLIC_METHODS)
    }
  }
}
