@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import com.labijie.orm.dummy.Status
import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable

/**
 * POJO for DescribeEnumTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.DescribeEnumTable
 */
@Serializable
public open class DescribeEnum {
  public var key1: String = ""

  public var key2: Int = 0

  public var status: Status = Status.OK
}
