@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import java.time.Duration
import kotlin.String

/**
 * POJO for DurationIdEntityTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.0.10
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.DurationIdEntityTable
 */
public open class DurationIdEntity {
  public var name: String = ""

  public var id: Duration = Duration.ZERO
}
