@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import com.labijie.infra.orm.serialization.OrmDuration
import java.time.Duration
import kotlin.String
import kotlinx.serialization.Serializable

/**
 * POJO for DurationIdEntityTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.1
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.DurationIdEntityTable
 */
@Serializable
public open class DurationIdEntity {
  public var name: String = ""

  public var id: OrmDuration = Duration.ZERO
}
