@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import kotlin.Int
import kotlin.String
import kotlinx.serialization.Serializable

/**
 * POJO for MultiKeyTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: unknown
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.MultiKeyTable
 */
@Serializable
public open class MultiKey {
  public var key1: String = ""

  public var key2: Int = 0
}
