@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import com.labijie.orm.dummy.TestEnum
import kotlin.Int
import kotlin.Long
import kotlin.String

/**
 * POJO for ShopTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.0.10
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.ShopTable
 */
public open class Shop {
  public var name: String = ""

  public var status: TestEnum = TestEnum.OK

  public var count: Int = 0

  public var id: Long = 0L
}
