@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import com.labijie.infra.orm.serialization.OrmBigDecimal
import com.labijie.infra.orm.serialization.OrmDuration
import com.labijie.infra.orm.serialization.OrmInstant
import com.labijie.infra.orm.serialization.OrmLocalDate
import com.labijie.infra.orm.serialization.OrmLocalDateTime
import com.labijie.infra.orm.serialization.OrmLocalTime
import com.labijie.infra.orm.serialization.OrmUUID
import com.labijie.orm.dummy.TestEnum
import com.labijie.orm.dummy.otherpackage.NestedInterface
import java.math.BigDecimal
import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.util.UUID
import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.Serializable

/**
 * POJO for TestTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.1
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.TestTable
 */
@Serializable
public open class Test {
  public var title: String? = null

  public var status: TestEnum = TestEnum.OK

  public var description: String = ""

  public var status2: NestedInterface.StatusEnum = NestedInterface.StatusEnum.Default

  public var array: List<String> = listOf()

  public var dateTime: OrmLocalDateTime = LocalDateTime.of(0, 1, 1, 0, 0,0, 0)

  public var duration: OrmDuration = Duration.ZERO

  public var time: OrmLocalTime = LocalTime.MIN

  public var date: OrmLocalDate = LocalDate.of(0, 1, 1)

  public var timestamp: OrmInstant = Instant.EPOCH

  public var decimal: OrmBigDecimal = BigDecimal.ZERO

  public var decimalNullable: OrmBigDecimal? = null

  public var uuid: OrmUUID = UUID(0L, 0L)

  public var uuidNullable: OrmUUID? = null

  public var datetime: OrmLocalDateTime = LocalDateTime.of(0, 1, 1, 0, 0,0, 0)

  public var datetimeNullable: OrmLocalDateTime? = null

  public var id: Long = 0L
}
