@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import com.labijie.infra.orm.serialization.OrmDuration
import com.labijie.infra.orm.serialization.OrmLocalDateTime
import com.labijie.infra.orm.serialization.OrmUUID
import com.labijie.orm.dummy.TestEnum
import java.time.Duration
import java.time.LocalDateTime
import java.util.UUID
import kotlin.Boolean
import kotlin.Byte
import kotlin.ByteArray
import kotlin.Char
import kotlin.Short
import kotlin.String
import kotlinx.serialization.Serializable

/**
 * POJO for TestSimpleTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: unknown
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.TestSimpleTable
 */
@Serializable
public open class TestSimple {
  public var name: String = ""

  public var memo: String? = null

  public var char: Char = '\u0000'

  public var text: String = ""

  public var `enum`: TestEnum = TestEnum.OK

  public var binary: ByteArray = ByteArray(0)

  public var uid: OrmUUID = UUID(0L, 0L)

  public var short: Short = 0

  public var bool: Boolean = false

  public var byte: Byte = 0

  public var dateTime: OrmLocalDateTime = LocalDateTime.of(0, 1, 1, 0, 0,0, 0)

  public var duration: OrmDuration = Duration.ZERO

  public var nameNullable: String? = null

  public var memoNullable: String? = null

  public var charNullable: Char? = null

  public var textNullable: String? = null

  public var enumNullable: TestEnum? = null

  public var binaryNullable: ByteArray? = null

  public var uidNullable: OrmUUID? = null

  public var shortNullable: Short? = null

  public var booleanNullable: Boolean? = null

  public var byteNullable: Byte? = null

  public var dateTimeNullable: OrmLocalDateTime? = null

  public var durationNullable: OrmDuration = Duration.ZERO

  public var id: String = ""
}
