@file:Suppress("RedundantVisibilityModifier")

package com.labijie.orm.dummy.pojo

import com.labijie.orm.dummy.TestEnum
import java.util.UUID
import kotlin.Boolean
import kotlin.Byte
import kotlin.ByteArray
import kotlin.Char
import kotlin.Short
import kotlin.String

/**
 * POJO for TestSimpleTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.0.10
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.orm.dummy.TestSimpleTable
 */
public open class TestSimple {
  public var name: String = ""

  public var memo: String? = null

  public var charCol: Char = '\u0000'

  public var textCol: String = ""

  public var enumCol: TestEnum = TestEnum.OK

  public var binaryCol: ByteArray = ByteArray(0)

  public var uidCol: UUID = UUID.randomUUID()

  public var shortCol: Short = 0

  public var booleanCol: Boolean = false

  public var byteCol: Byte = 0

  public var id: String = ""
}
